/*
 * Copyright (c) 2010-2012 LinkedIn, Inc
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package krati.io;

/**
 * An interface for object serialization.
 * 
 * @author jwu
 * 06/29, 2011
 * 
 * @param <T> An object to serialize.
 */
public interface Serializer<T> {
    
    /**
     * Serialize an object into a byte array.
     * 
     * @param object - an object to be serialized by this Serializer.
     * @return a byte array which is the raw representation of an object.
     */
    public byte[] serialize(T object) throws SerializationException;
    
    /**
     * Deserialize an object from its raw bytes generated by {{@link #serialize(Object)}.
     * 
     * @param bytes - the raw bytes from which an object is constructed.
     * @return an object constructed from the raw bytes.
     * @throws SerializationException if the object cannot be constructed from the raw bytes.
     */
    public T deserialize(byte[] bytes) throws SerializationException;
}
