// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/protos/Member.proto

package test.protos;

public final class MemberProtos {
  private MemberProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Member extends
      com.google.protobuf.GeneratedMessage {
    // Use Member.newBuilder() to construct.
    private Member() {
      initFields();
    }
    private Member(boolean noInit) {}
    
    private static final Member defaultInstance;
    public static Member getDefaultInstance() {
      return defaultInstance;
    }
    
    public Member getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.protos.MemberProtos.internal_static_test_protos_Member_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.protos.MemberProtos.internal_static_test_protos_Member_fieldAccessorTable;
    }
    
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      MOBILE(0, 0),
      HOME(1, 1),
      WORK(2, 2),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static PhoneType valueOf(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORK;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return test.protos.MemberProtos.Member.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final PhoneType[] VALUES = {
        MOBILE, HOME, WORK, 
      };
      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private PhoneType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        test.protos.MemberProtos.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:test.protos.Member.PhoneType)
    }
    
    public static final class PhoneNumber extends
        com.google.protobuf.GeneratedMessage {
      // Use PhoneNumber.newBuilder() to construct.
      private PhoneNumber() {
        initFields();
      }
      private PhoneNumber(boolean noInit) {}
      
      private static final PhoneNumber defaultInstance;
      public static PhoneNumber getDefaultInstance() {
        return defaultInstance;
      }
      
      public PhoneNumber getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.protos.MemberProtos.internal_static_test_protos_Member_PhoneNumber_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.protos.MemberProtos.internal_static_test_protos_Member_PhoneNumber_fieldAccessorTable;
      }
      
      // required string number = 1;
      public static final int NUMBER_FIELD_NUMBER = 1;
      private boolean hasNumber;
      private java.lang.String number_ = "";
      public boolean hasNumber() { return hasNumber; }
      public java.lang.String getNumber() { return number_; }
      
      // optional .test.protos.Member.PhoneType type = 2 [default = HOME];
      public static final int TYPE_FIELD_NUMBER = 2;
      private boolean hasType;
      private test.protos.MemberProtos.Member.PhoneType type_;
      public boolean hasType() { return hasType; }
      public test.protos.MemberProtos.Member.PhoneType getType() { return type_; }
      
      private void initFields() {
        type_ = test.protos.MemberProtos.Member.PhoneType.HOME;
      }
      public final boolean isInitialized() {
        if (!hasNumber) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasNumber()) {
          output.writeString(1, getNumber());
        }
        if (hasType()) {
          output.writeEnum(2, getType().getNumber());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getNumber());
        }
        if (hasType()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, getType().getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static test.protos.MemberProtos.Member.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static test.protos.MemberProtos.Member.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static test.protos.MemberProtos.Member.PhoneNumber parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static test.protos.MemberProtos.Member.PhoneNumber parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static test.protos.MemberProtos.Member.PhoneNumber parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static test.protos.MemberProtos.Member.PhoneNumber parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static test.protos.MemberProtos.Member.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static test.protos.MemberProtos.Member.PhoneNumber parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static test.protos.MemberProtos.Member.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static test.protos.MemberProtos.Member.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(test.protos.MemberProtos.Member.PhoneNumber prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private test.protos.MemberProtos.Member.PhoneNumber result;
        
        // Construct using test.protos.MemberProtos.Member.PhoneNumber.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new test.protos.MemberProtos.Member.PhoneNumber();
          return builder;
        }
        
        protected test.protos.MemberProtos.Member.PhoneNumber internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new test.protos.MemberProtos.Member.PhoneNumber();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return test.protos.MemberProtos.Member.PhoneNumber.getDescriptor();
        }
        
        public test.protos.MemberProtos.Member.PhoneNumber getDefaultInstanceForType() {
          return test.protos.MemberProtos.Member.PhoneNumber.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public test.protos.MemberProtos.Member.PhoneNumber build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private test.protos.MemberProtos.Member.PhoneNumber buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public test.protos.MemberProtos.Member.PhoneNumber buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          test.protos.MemberProtos.Member.PhoneNumber returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof test.protos.MemberProtos.Member.PhoneNumber) {
            return mergeFrom((test.protos.MemberProtos.Member.PhoneNumber)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(test.protos.MemberProtos.Member.PhoneNumber other) {
          if (other == test.protos.MemberProtos.Member.PhoneNumber.getDefaultInstance()) return this;
          if (other.hasNumber()) {
            setNumber(other.getNumber());
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setNumber(input.readString());
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                test.protos.MemberProtos.Member.PhoneType value = test.protos.MemberProtos.Member.PhoneType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  setType(value);
                }
                break;
              }
            }
          }
        }
        
        
        // required string number = 1;
        public boolean hasNumber() {
          return result.hasNumber();
        }
        public java.lang.String getNumber() {
          return result.getNumber();
        }
        public Builder setNumber(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasNumber = true;
          result.number_ = value;
          return this;
        }
        public Builder clearNumber() {
          result.hasNumber = false;
          result.number_ = getDefaultInstance().getNumber();
          return this;
        }
        
        // optional .test.protos.Member.PhoneType type = 2 [default = HOME];
        public boolean hasType() {
          return result.hasType();
        }
        public test.protos.MemberProtos.Member.PhoneType getType() {
          return result.getType();
        }
        public Builder setType(test.protos.MemberProtos.Member.PhoneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          result.hasType = true;
          result.type_ = value;
          return this;
        }
        public Builder clearType() {
          result.hasType = false;
          result.type_ = test.protos.MemberProtos.Member.PhoneType.HOME;
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:test.protos.Member.PhoneNumber)
      }
      
      static {
        defaultInstance = new PhoneNumber(true);
        test.protos.MemberProtos.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:test.protos.Member.PhoneNumber)
    }
    
    // required int32 member_id = 1;
    public static final int MEMBER_ID_FIELD_NUMBER = 1;
    private boolean hasMemberId;
    private int memberId_ = 0;
    public boolean hasMemberId() { return hasMemberId; }
    public int getMemberId() { return memberId_; }
    
    // optional string last_name = 2;
    public static final int LAST_NAME_FIELD_NUMBER = 2;
    private boolean hasLastName;
    private java.lang.String lastName_ = "";
    public boolean hasLastName() { return hasLastName; }
    public java.lang.String getLastName() { return lastName_; }
    
    // optional string first_name = 3;
    public static final int FIRST_NAME_FIELD_NUMBER = 3;
    private boolean hasFirstName;
    private java.lang.String firstName_ = "";
    public boolean hasFirstName() { return hasFirstName; }
    public java.lang.String getFirstName() { return firstName_; }
    
    // repeated string email = 4;
    public static final int EMAIL_FIELD_NUMBER = 4;
    private java.util.List<java.lang.String> email_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getEmailList() {
      return email_;
    }
    public int getEmailCount() { return email_.size(); }
    public java.lang.String getEmail(int index) {
      return email_.get(index);
    }
    
    // repeated .test.protos.Member.PhoneNumber phone = 5;
    public static final int PHONE_FIELD_NUMBER = 5;
    private java.util.List<test.protos.MemberProtos.Member.PhoneNumber> phone_ =
      java.util.Collections.emptyList();
    public java.util.List<test.protos.MemberProtos.Member.PhoneNumber> getPhoneList() {
      return phone_;
    }
    public int getPhoneCount() { return phone_.size(); }
    public test.protos.MemberProtos.Member.PhoneNumber getPhone(int index) {
      return phone_.get(index);
    }
    
    // repeated string job_title = 7;
    public static final int JOB_TITLE_FIELD_NUMBER = 7;
    private java.util.List<java.lang.String> jobTitle_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getJobTitleList() {
      return jobTitle_;
    }
    public int getJobTitleCount() { return jobTitle_.size(); }
    public java.lang.String getJobTitle(int index) {
      return jobTitle_.get(index);
    }
    
    // optional string profile = 8 [default = "N/A"];
    public static final int PROFILE_FIELD_NUMBER = 8;
    private boolean hasProfile;
    private java.lang.String profile_ = "N/A";
    public boolean hasProfile() { return hasProfile; }
    public java.lang.String getProfile() { return profile_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasMemberId) return false;
      for (test.protos.MemberProtos.Member.PhoneNumber element : getPhoneList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasMemberId()) {
        output.writeInt32(1, getMemberId());
      }
      if (hasLastName()) {
        output.writeString(2, getLastName());
      }
      if (hasFirstName()) {
        output.writeString(3, getFirstName());
      }
      for (java.lang.String element : getEmailList()) {
        output.writeString(4, element);
      }
      for (test.protos.MemberProtos.Member.PhoneNumber element : getPhoneList()) {
        output.writeMessage(5, element);
      }
      for (java.lang.String element : getJobTitleList()) {
        output.writeString(7, element);
      }
      if (hasProfile()) {
        output.writeString(8, getProfile());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasMemberId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getMemberId());
      }
      if (hasLastName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getLastName());
      }
      if (hasFirstName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getFirstName());
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getEmailList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getEmailList().size();
      }
      for (test.protos.MemberProtos.Member.PhoneNumber element : getPhoneList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, element);
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getJobTitleList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getJobTitleList().size();
      }
      if (hasProfile()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getProfile());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static test.protos.MemberProtos.Member parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static test.protos.MemberProtos.Member parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static test.protos.MemberProtos.Member parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static test.protos.MemberProtos.Member parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static test.protos.MemberProtos.Member parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static test.protos.MemberProtos.Member parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static test.protos.MemberProtos.Member parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static test.protos.MemberProtos.Member parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static test.protos.MemberProtos.Member parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static test.protos.MemberProtos.Member parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(test.protos.MemberProtos.Member prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private test.protos.MemberProtos.Member result;
      
      // Construct using test.protos.MemberProtos.Member.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new test.protos.MemberProtos.Member();
        return builder;
      }
      
      protected test.protos.MemberProtos.Member internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new test.protos.MemberProtos.Member();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.protos.MemberProtos.Member.getDescriptor();
      }
      
      public test.protos.MemberProtos.Member getDefaultInstanceForType() {
        return test.protos.MemberProtos.Member.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public test.protos.MemberProtos.Member build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private test.protos.MemberProtos.Member buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public test.protos.MemberProtos.Member buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.email_ != java.util.Collections.EMPTY_LIST) {
          result.email_ =
            java.util.Collections.unmodifiableList(result.email_);
        }
        if (result.phone_ != java.util.Collections.EMPTY_LIST) {
          result.phone_ =
            java.util.Collections.unmodifiableList(result.phone_);
        }
        if (result.jobTitle_ != java.util.Collections.EMPTY_LIST) {
          result.jobTitle_ =
            java.util.Collections.unmodifiableList(result.jobTitle_);
        }
        test.protos.MemberProtos.Member returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.protos.MemberProtos.Member) {
          return mergeFrom((test.protos.MemberProtos.Member)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(test.protos.MemberProtos.Member other) {
        if (other == test.protos.MemberProtos.Member.getDefaultInstance()) return this;
        if (other.hasMemberId()) {
          setMemberId(other.getMemberId());
        }
        if (other.hasLastName()) {
          setLastName(other.getLastName());
        }
        if (other.hasFirstName()) {
          setFirstName(other.getFirstName());
        }
        if (!other.email_.isEmpty()) {
          if (result.email_.isEmpty()) {
            result.email_ = new java.util.ArrayList<java.lang.String>();
          }
          result.email_.addAll(other.email_);
        }
        if (!other.phone_.isEmpty()) {
          if (result.phone_.isEmpty()) {
            result.phone_ = new java.util.ArrayList<test.protos.MemberProtos.Member.PhoneNumber>();
          }
          result.phone_.addAll(other.phone_);
        }
        if (!other.jobTitle_.isEmpty()) {
          if (result.jobTitle_.isEmpty()) {
            result.jobTitle_ = new java.util.ArrayList<java.lang.String>();
          }
          result.jobTitle_.addAll(other.jobTitle_);
        }
        if (other.hasProfile()) {
          setProfile(other.getProfile());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setMemberId(input.readInt32());
              break;
            }
            case 18: {
              setLastName(input.readString());
              break;
            }
            case 26: {
              setFirstName(input.readString());
              break;
            }
            case 34: {
              addEmail(input.readString());
              break;
            }
            case 42: {
              test.protos.MemberProtos.Member.PhoneNumber.Builder subBuilder = test.protos.MemberProtos.Member.PhoneNumber.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPhone(subBuilder.buildPartial());
              break;
            }
            case 58: {
              addJobTitle(input.readString());
              break;
            }
            case 66: {
              setProfile(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required int32 member_id = 1;
      public boolean hasMemberId() {
        return result.hasMemberId();
      }
      public int getMemberId() {
        return result.getMemberId();
      }
      public Builder setMemberId(int value) {
        result.hasMemberId = true;
        result.memberId_ = value;
        return this;
      }
      public Builder clearMemberId() {
        result.hasMemberId = false;
        result.memberId_ = 0;
        return this;
      }
      
      // optional string last_name = 2;
      public boolean hasLastName() {
        return result.hasLastName();
      }
      public java.lang.String getLastName() {
        return result.getLastName();
      }
      public Builder setLastName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLastName = true;
        result.lastName_ = value;
        return this;
      }
      public Builder clearLastName() {
        result.hasLastName = false;
        result.lastName_ = getDefaultInstance().getLastName();
        return this;
      }
      
      // optional string first_name = 3;
      public boolean hasFirstName() {
        return result.hasFirstName();
      }
      public java.lang.String getFirstName() {
        return result.getFirstName();
      }
      public Builder setFirstName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasFirstName = true;
        result.firstName_ = value;
        return this;
      }
      public Builder clearFirstName() {
        result.hasFirstName = false;
        result.firstName_ = getDefaultInstance().getFirstName();
        return this;
      }
      
      // repeated string email = 4;
      public java.util.List<java.lang.String> getEmailList() {
        return java.util.Collections.unmodifiableList(result.email_);
      }
      public int getEmailCount() {
        return result.getEmailCount();
      }
      public java.lang.String getEmail(int index) {
        return result.getEmail(index);
      }
      public Builder setEmail(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.email_.set(index, value);
        return this;
      }
      public Builder addEmail(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.email_.isEmpty()) {
          result.email_ = new java.util.ArrayList<java.lang.String>();
        }
        result.email_.add(value);
        return this;
      }
      public Builder addAllEmail(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.email_.isEmpty()) {
          result.email_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.email_);
        return this;
      }
      public Builder clearEmail() {
        result.email_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .test.protos.Member.PhoneNumber phone = 5;
      public java.util.List<test.protos.MemberProtos.Member.PhoneNumber> getPhoneList() {
        return java.util.Collections.unmodifiableList(result.phone_);
      }
      public int getPhoneCount() {
        return result.getPhoneCount();
      }
      public test.protos.MemberProtos.Member.PhoneNumber getPhone(int index) {
        return result.getPhone(index);
      }
      public Builder setPhone(int index, test.protos.MemberProtos.Member.PhoneNumber value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.phone_.set(index, value);
        return this;
      }
      public Builder setPhone(int index, test.protos.MemberProtos.Member.PhoneNumber.Builder builderForValue) {
        result.phone_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPhone(test.protos.MemberProtos.Member.PhoneNumber value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.phone_.isEmpty()) {
          result.phone_ = new java.util.ArrayList<test.protos.MemberProtos.Member.PhoneNumber>();
        }
        result.phone_.add(value);
        return this;
      }
      public Builder addPhone(test.protos.MemberProtos.Member.PhoneNumber.Builder builderForValue) {
        if (result.phone_.isEmpty()) {
          result.phone_ = new java.util.ArrayList<test.protos.MemberProtos.Member.PhoneNumber>();
        }
        result.phone_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPhone(
          java.lang.Iterable<? extends test.protos.MemberProtos.Member.PhoneNumber> values) {
        if (result.phone_.isEmpty()) {
          result.phone_ = new java.util.ArrayList<test.protos.MemberProtos.Member.PhoneNumber>();
        }
        super.addAll(values, result.phone_);
        return this;
      }
      public Builder clearPhone() {
        result.phone_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated string job_title = 7;
      public java.util.List<java.lang.String> getJobTitleList() {
        return java.util.Collections.unmodifiableList(result.jobTitle_);
      }
      public int getJobTitleCount() {
        return result.getJobTitleCount();
      }
      public java.lang.String getJobTitle(int index) {
        return result.getJobTitle(index);
      }
      public Builder setJobTitle(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.jobTitle_.set(index, value);
        return this;
      }
      public Builder addJobTitle(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.jobTitle_.isEmpty()) {
          result.jobTitle_ = new java.util.ArrayList<java.lang.String>();
        }
        result.jobTitle_.add(value);
        return this;
      }
      public Builder addAllJobTitle(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.jobTitle_.isEmpty()) {
          result.jobTitle_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.jobTitle_);
        return this;
      }
      public Builder clearJobTitle() {
        result.jobTitle_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional string profile = 8 [default = "N/A"];
      public boolean hasProfile() {
        return result.hasProfile();
      }
      public java.lang.String getProfile() {
        return result.getProfile();
      }
      public Builder setProfile(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasProfile = true;
        result.profile_ = value;
        return this;
      }
      public Builder clearProfile() {
        result.hasProfile = false;
        result.profile_ = getDefaultInstance().getProfile();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:test.protos.Member)
    }
    
    static {
      defaultInstance = new Member(true);
      test.protos.MemberProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:test.protos.Member)
  }
  
  public static final class MemberBook extends
      com.google.protobuf.GeneratedMessage {
    // Use MemberBook.newBuilder() to construct.
    private MemberBook() {
      initFields();
    }
    private MemberBook(boolean noInit) {}
    
    private static final MemberBook defaultInstance;
    public static MemberBook getDefaultInstance() {
      return defaultInstance;
    }
    
    public MemberBook getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.protos.MemberProtos.internal_static_test_protos_MemberBook_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.protos.MemberProtos.internal_static_test_protos_MemberBook_fieldAccessorTable;
    }
    
    // repeated .test.protos.Member member = 1;
    public static final int MEMBER_FIELD_NUMBER = 1;
    private java.util.List<test.protos.MemberProtos.Member> member_ =
      java.util.Collections.emptyList();
    public java.util.List<test.protos.MemberProtos.Member> getMemberList() {
      return member_;
    }
    public int getMemberCount() { return member_.size(); }
    public test.protos.MemberProtos.Member getMember(int index) {
      return member_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      for (test.protos.MemberProtos.Member element : getMemberList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (test.protos.MemberProtos.Member element : getMemberList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (test.protos.MemberProtos.Member element : getMemberList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static test.protos.MemberProtos.MemberBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static test.protos.MemberProtos.MemberBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static test.protos.MemberProtos.MemberBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static test.protos.MemberProtos.MemberBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static test.protos.MemberProtos.MemberBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static test.protos.MemberProtos.MemberBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static test.protos.MemberProtos.MemberBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static test.protos.MemberProtos.MemberBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static test.protos.MemberProtos.MemberBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static test.protos.MemberProtos.MemberBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(test.protos.MemberProtos.MemberBook prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private test.protos.MemberProtos.MemberBook result;
      
      // Construct using test.protos.MemberProtos.MemberBook.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new test.protos.MemberProtos.MemberBook();
        return builder;
      }
      
      protected test.protos.MemberProtos.MemberBook internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new test.protos.MemberProtos.MemberBook();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.protos.MemberProtos.MemberBook.getDescriptor();
      }
      
      public test.protos.MemberProtos.MemberBook getDefaultInstanceForType() {
        return test.protos.MemberProtos.MemberBook.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public test.protos.MemberProtos.MemberBook build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private test.protos.MemberProtos.MemberBook buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public test.protos.MemberProtos.MemberBook buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.member_ != java.util.Collections.EMPTY_LIST) {
          result.member_ =
            java.util.Collections.unmodifiableList(result.member_);
        }
        test.protos.MemberProtos.MemberBook returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.protos.MemberProtos.MemberBook) {
          return mergeFrom((test.protos.MemberProtos.MemberBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(test.protos.MemberProtos.MemberBook other) {
        if (other == test.protos.MemberProtos.MemberBook.getDefaultInstance()) return this;
        if (!other.member_.isEmpty()) {
          if (result.member_.isEmpty()) {
            result.member_ = new java.util.ArrayList<test.protos.MemberProtos.Member>();
          }
          result.member_.addAll(other.member_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              test.protos.MemberProtos.Member.Builder subBuilder = test.protos.MemberProtos.Member.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMember(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .test.protos.Member member = 1;
      public java.util.List<test.protos.MemberProtos.Member> getMemberList() {
        return java.util.Collections.unmodifiableList(result.member_);
      }
      public int getMemberCount() {
        return result.getMemberCount();
      }
      public test.protos.MemberProtos.Member getMember(int index) {
        return result.getMember(index);
      }
      public Builder setMember(int index, test.protos.MemberProtos.Member value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.member_.set(index, value);
        return this;
      }
      public Builder setMember(int index, test.protos.MemberProtos.Member.Builder builderForValue) {
        result.member_.set(index, builderForValue.build());
        return this;
      }
      public Builder addMember(test.protos.MemberProtos.Member value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.member_.isEmpty()) {
          result.member_ = new java.util.ArrayList<test.protos.MemberProtos.Member>();
        }
        result.member_.add(value);
        return this;
      }
      public Builder addMember(test.protos.MemberProtos.Member.Builder builderForValue) {
        if (result.member_.isEmpty()) {
          result.member_ = new java.util.ArrayList<test.protos.MemberProtos.Member>();
        }
        result.member_.add(builderForValue.build());
        return this;
      }
      public Builder addAllMember(
          java.lang.Iterable<? extends test.protos.MemberProtos.Member> values) {
        if (result.member_.isEmpty()) {
          result.member_ = new java.util.ArrayList<test.protos.MemberProtos.Member>();
        }
        super.addAll(values, result.member_);
        return this;
      }
      public Builder clearMember() {
        result.member_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:test.protos.MemberBook)
    }
    
    static {
      defaultInstance = new MemberBook(true);
      test.protos.MemberProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:test.protos.MemberBook)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_protos_Member_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_protos_Member_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_protos_Member_PhoneNumber_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_protos_Member_PhoneNumber_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_protos_MemberBook_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_protos_MemberBook_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030test/protos/Member.proto\022\013test.protos\"" +
      "\251\002\n\006Member\022\021\n\tmember_id\030\001 \002(\005\022\021\n\tlast_na" +
      "me\030\002 \001(\t\022\022\n\nfirst_name\030\003 \001(\t\022\r\n\005email\030\004 " +
      "\003(\t\022.\n\005phone\030\005 \003(\0132\037.test.protos.Member." +
      "PhoneNumber\022\021\n\tjob_title\030\007 \003(\t\022\024\n\007profil" +
      "e\030\010 \001(\t:\003N/A\032P\n\013PhoneNumber\022\016\n\006number\030\001 " +
      "\002(\t\0221\n\004type\030\002 \001(\0162\035.test.protos.Member.P" +
      "honeType:\004HOME\"+\n\tPhoneType\022\n\n\006MOBILE\020\000\022" +
      "\010\n\004HOME\020\001\022\010\n\004WORK\020\002\"1\n\nMemberBook\022#\n\006mem" +
      "ber\030\001 \003(\0132\023.test.protos.MemberB\033\n\013test.p",
      "rotosB\014MemberProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_test_protos_Member_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_test_protos_Member_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_test_protos_Member_descriptor,
              new java.lang.String[] { "MemberId", "LastName", "FirstName", "Email", "Phone", "JobTitle", "Profile", },
              test.protos.MemberProtos.Member.class,
              test.protos.MemberProtos.Member.Builder.class);
          internal_static_test_protos_Member_PhoneNumber_descriptor =
            internal_static_test_protos_Member_descriptor.getNestedTypes().get(0);
          internal_static_test_protos_Member_PhoneNumber_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_test_protos_Member_PhoneNumber_descriptor,
              new java.lang.String[] { "Number", "Type", },
              test.protos.MemberProtos.Member.PhoneNumber.class,
              test.protos.MemberProtos.Member.PhoneNumber.Builder.class);
          internal_static_test_protos_MemberBook_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_test_protos_MemberBook_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_test_protos_MemberBook_descriptor,
              new java.lang.String[] { "Member", },
              test.protos.MemberProtos.MemberBook.class,
              test.protos.MemberProtos.MemberBook.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
